/**
 * Esmaül Hüsna — varsayılan fazilet metinleri (99), ESMA_LIST sırasıyla.
 */
export const ESMA_DEFAULT_FAZILET = [
    "Tevhid ve ihlâsı pekiştirir; kalbi Allah’tan başka meşguliyetten arındırmaya yardım eder.",
    "Rahmet ümidini artırır; kullara merhamet etmeyi ve affı hatırlatır.",
    "Ahiret müjdesi ve mağfiret ümidini canlı tutar; bağışlanma dilemeyi hatırlatır.",
    "Hak ve adaletle hükmeten tek malik olduğunu hatırlatır; kalpte Allah’a teslimiyeti artırır.",
    "Noksanlıktan uzaklığı düşünerek Allah’ı tenzih etmeyi (tesbih) pekiştirir.",
    "Selâmet ve esenlik duasını hatırlatır; korku ve endişede O’na sığınmayı güçlendirir.",
    "Güven ve emniyet duygusunu artırır; kalbi Allah’a dayanmaya yönlendirir.",
    "Her şeyi gözeten olduğunu hatırlatır; gizliyi açığı bilen bilinci uyandırır.",
    "Galib ve izzet sahibi olduğunu hatırlatır; zulme karşı Allah’a sığınmayı pekiştirir.",
    "Dilediğini yapan güçlü olduğunu hatırlatır; boyun eğiş ve tevazuu canlı tutar.",
    "Büyüklük yalnız Allah’a mahsustur bilincini pekiştirir; kibre karşı tevazu hatırlatır.",
    "Yaratan olduğunu düşünmek şükür ve hayret duygusunu artırır.",
    "Yarattığını kusursuz biçimde var eden olduğunu hatırlatır.",
    "Her şeye şekil veren sanat ve düzeni hatırlatır; yaratılış âyetlerine dikkati artırır.",
    "Mağfiret ümidini besler; tövbe ve istiğfarı canlı tutar.",
    "Her şeye galip güç olduğunu hatırlatır; zulüm ve fitneye karşı O’na sığınmayı güçlendirir.",
    "Karşılıksız ihsân ve lütuf ümidini artırır; cömertliği hatırlatır.",
    "Rızık endişesinde Allah’a tevekkülü pekiştirir; rızık veren olduğunu hatırlatır.",
    "Kilitleri açan ve sıkıntıdan çıkış veren olduğuna güveni artırır.",
    "Gizliyi açığı bilen olduğunu hatırlatır; ilim ve hikmet talebini canlı tutar.",
    "Dilediğine darlık verebilen güç olduğunu hatırlatır; israf ve taşkınlıktan sakınmayı güçlendirir.",
    "Genişlik ve bolluk veren olduğunu hatırlatır; cömertlik ve infâkı canlı tutar.",
    "Alçaltan ve yükseltenin Allah olduğunu hatırlatır; tevazu ve adaleti pekiştirir.",
    "İmanlıları yükselten dilediğini yücelten olduğunu hatırlatır.",
    "İzzet ve şeref veren olduğunu düşünmek kalbi O’na yönlendirir.",
    "Dilediğini alçaltan olduğunu hatırlatır; kibre ve zulme karşı Allah’a sığınmayı artırır.",
    "Duaları işiten olduğunu hatırlatır; içten niyaz ve yalvarmayı canlı tutar.",
    "Her şeyi gören olduğunu hatırlatır; gizli açık takva bilincini pekiştirir.",
    "Hüküm ve adaletin hakiki sahibi olduğunu hatırlatır.",
    "Mutlak adil olduğunu hatırlatır; haksızlıktan sakınmayı güçlendirir.",
    "İnce lütuf ve yardım sahibi olduğunu hatırlatır; ümitsizlikte ümit beslemeyi artırır.",
    "Her şeyden haberdar olduğunu hatırlatır; gizliyi bilen bilinci canlı tutar.",
    "Aceleyle cezalandırmayan sabırlı olduğunu hatırlatır; öfkeyi dizginlemeyi destekler.",
    "Azamet ve yücelik sahibi olduğunu hatırlatır; kalpte Allah’a hürmeti artırır.",
    "Mağfiret ve bağışlama ümidini besler; tövbe ve istiğfarı canlı tutar.",
    "Az şükürle çok mükâfât veren olduğunu hatırlatır; şükür ve hamdi artırır.",
    "Yücelik ve üstünlüğün hakiki sahibi olduğunu hatırlatır.",
    "Büyük olan yalnız O’dur bilincini pekiştirir; kalpte tevhidi güçlendirir.",
    "Koruyan ve muhafaza eden olduğunu hatırlatır; endişede O’na dayanmayı artırır.",
    "Rızık ve ölçüyü veren olduğunu hatırlatır; israf etmemeyi canlı tutar.",
    "Hesap gününü hatırlatır; amellerin karşılığını veren bilinci pekiştirir.",
    "Celâl ve yücelik sıfatlarını hatırlatır; Allah’a hürmet ve haşyet duygusunu artırır.",
    "İkram ve lütuf sahibi olduğunu hatırlatır; cömertliği ve ihsânı canlı tutar.",
    "Gözetleyen ve gören olduğunu hatırlatır; gizli açık takvayı pekiştirir.",
    "Duaları kabul eden olduğuna ümidi artırır; yakarış ve niyazı canlı tutar.",
    "Rahmeti ve ilmi geniş olan olduğunu hatırlatır; ümidi ve merhameti artırır.",
    "Her işte hikmet sahibi olduğunu hatırlatır; başa gelenlere sabır ve tevekkülü destekler.",
    "Kullarını seven olduğunu hatırlatır; Allah sevgisi ve O’na yönelmeyi pekiştirir.",
    "Şanı yüce ve övgüye layık olduğunu hatırlatır; hamd ve tesbihi canlı tutar.",
    "Ölümden sonra diriltip hesaba çekecek olduğunu hatırlatır.",
    "Gizliyi açığı şahit olan olduğunu hatırlatır; doğruluk ve dürüstlüğü pekiştirir.",
    "Hak olan ve hakkı gösteren olduğunu hatırlatır; adaleti ve doğruluğu canlı tutar.",
    "İşleri güzelce yürüten ve tevekkül edilen vekîl olduğunu hatırlatır.",
    "Kudreti tam olan olduğunu hatırlatır; zayıflıkta O’ndan güç diler.",
    "Sağlam ve güçlü olduğunu hatırlatır; korku ve fitnede O’na sığınmayı artırır.",
    "Müminlere dost ve velî olduğunu hatırlatır; Allah’a yönelmeyi pekiştirir.",
    "Övgüye layık hamd edilen olduğunu hatırlatır; şükür ve hamdi artırır.",
    "Sayıp ölçen ve hesabını bilen olduğunu hatırlatır; amele dikkati artırır.",
    "Yoktan var eden başlangıcı hatırlatır; yaratılış mucizesine hayret duygusunu artırır.",
    "Sonu ve dönüşü hatırlatır; ahiret bilincini canlı tutar.",
    "Dirilten ve hayat veren olduğunu hatırlatır; ümidi ve hayat bağlılığını pekiştirir.",
    "Ölümü ve sonu hatırlatır; dünya bağını hafifletir, ahireti öne alır.",
    "Diri ve her şeye hayat kaynağı olan olduğunu hatırlatır.",
    "Her şeyi ayakta tutan ve yöneten olduğunu hatırlatır; tevekkülü pekiştirir.",
    "Her ihtiyacı karşılayan ve bulan olduğunu hatırlatır; rızık ve ümidi artırır.",
    "Şanı yüce ve övülen olduğunu hatırlatır; hamd ve tesbihi canlı tutar.",
    "Tek ve benzersiz olduğunu hatırlatır; şirkten ve çoğaltmaktan sakınmayı güçlendirir.",
    "Muhtaç olunan ve ihtiyaçların giderildiği merci olduğunu hatırlatır.",
    "Dilediğini yapmaya gücü yeten olduğunu hatırlatır; Allah’a güveni artırır.",
    "İradesi her şeye galip olan güç sahibi olduğunu hatırlatır.",
    "Dilediğini öne alan ve yükselten olduğunu hatırlatır.",
    "Dilediğini geri bırakan ve tehir eden olduğunu hatırlatır; hikmete teslimiyeti pekiştirir.",
    "Öncesi olmayan başlangıcı hatırlatır; tevhid ve yaratılış bilincini artırır.",
    "Sonsuz sonu hatırlatır; dünya geçiciliğini ve ahireti öne alır.",
    "Açık ve görünen âyetlerini ve varlığını hatırlatır.",
    "Gaybı ve iç yüzü bilen olduğunu hatırlatır; kalpte takvayı pekiştirir.",
    "Her şeyin gerçek sahibi ve yöneticisi olduğunu hatırlatır.",
    "Yüceliği üstün olan olduğunu hatırlatır; Allah’a hürmet ve tevazu pekişir.",
    "İyilik ve ihsânı bol olan olduğunu hatırlatır; kullara iyiliği canlı tutar.",
    "Tövbeleri kabul eden olduğunu hatırlatır; tövbe ve ümidi artırır.",
    "Hakkı yerine getiren ve intikam sahibi olduğunu hatırlatır; zulme karşı adaleti pekiştirir.",
    "Affı bol olan olduğunu hatırlatır; bağışlanma dilemeyi canlı tutar.",
    "Merhameti derin olan olduğunu hatırlatır; merhamet ve şefkati artırır.",
    "Gerçek mülk ve saltanat sahibi olduğunu hatırlatır; kalpte tevhidi pekiştirir.",
    "Celâl ve ikram sahibi olduğunu hatırlatır; O’na hürmet ve şükür duygusunu artırır.",
    "Adaleti yerine getiren olduğunu hatırlatır; hakkı gözetmeyi canlı tutar.",
    "Kıyamette ve dünyada bir araya getiren olduğunu hatırlatır; birlik ve kardeşliği pekiştirir.",
    "Hiçbir şeye muhtaç olmayan zengin olduğunu hatırlatır; kalpte tevekkülü artırır.",
    "Muhtaçları zenginleştiren olduğunu hatırlatır; fakir ve muhtaçlara merhameti artırır.",
    "Dilediğine engel olan güç sahibi olduğunu hatırlatır; Allah’a sığınmayı pekiştirir.",
    "Zarar verebilen güç olduğunu hatırlatır; günah ve isyandan sakınmayı güçlendirir.",
    "Fayda ve hayır veren olduğunu hatırlatır; iyilik yapmayı canlı tutar.",
    "Alemleri aydınlatan nur olduğunu hatırlatır; hidayet ve doğru yolu aramayı artırır.",
    "Hidayet veren ve doğru yola erdiren olduğunu hatırlatır.",
    "Eşi benzeri olmayan şekilde yaratan olduğunu hatırlatır; yaratılış hayretini artırır.",
    "Varlığı sonsuz süren olduğunu hatırlatır; geçicilikte Allah’a yönelmeyi pekiştirir.",
    "Her şeyin sonunda gerçek mirasçı ve sahibi olduğunu hatırlatır.",
    "Doğru yolu gösteren olduğunu hatırlatır; şaşkınlıkta O’na yönelmeyi artırır.",
    "Acele etmeden sabırla hükmeden olduğunu hatırlatır; sabır ve metanet pekişir."
];
